name: Keep Streamlit App Awake

on:
  schedule:
    # This runs every 60 minutes. 
    # You can change '0' to '*/30' for every 30 mins if needed.
    - cron: '*/10 * * * *' 
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to app
        run: |
          curl -I https://movie-recommendation-system-by-kalpesh-nankar.streamlit.app/
          